version: '3'
services:
  app:
    image: node:16-alpine
    command: yarn start
    container_name: strapi
    labels:
      com.example.description: "Strapi project"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: app
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: toor
      JWT_SECRET: secret
      JWT_EXPIRATION_TIME: 86400
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - db
    working_dir: /srv/app

  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    volumes:
      - ./data:/var/lib/postgresql/data
